# THEME

# Option 1:  DuskFox
# upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/duskfox/alacritty.toml

 [colors.primary]
 background = "#232136"
 foreground = "#e0def4"
 dim_foreground = "#cdcbe0"
 bright_foreground = "#eae8ff"
 
 [colors.cursor]
 text = "#e0def4"
 cursor = "#cdcbe0"
 
 [colors.vi_mode_cursor]
 text = "#e0def4"
 cursor = "#9ccfd8"
 
 [colors.search.matches]
 foreground = "#e0def4"
 background = "#63577d"
 
 [colors.search.focused_match]
 foreground = "#e0def4"
 background = "#a3be8c"
 
 [colors.footer_bar]
 foreground = "#e0def4"
 background = "#373354"
 
 [colors.hints.start]
 foreground = "#e0def4"
 background = "#ea9a97"
 
 [colors.hints.end]
 foreground = "#e0def4"
 background = "#373354"
 
 [colors.selection]
 text = "#e0def4"
 background = "#433c59"
 
 [colors.normal]
 black = "#393552"
 red = "#eb6f92"
 green = "#a3be8c"
 yellow = "#f6c177"
 blue = "#569fba"
 magenta = "#c4a7e7"
 cyan = "#9ccfd8"
 white = "#e0def4"
 
 [colors.bright]
 black = "#47407d"
 red = "#f083a2"
 green = "#b1d196"
 yellow = "#f9cb8c"
 blue = "#65b1cd"
 magenta = "#ccb1ed"
 cyan = "#a6dae3"
 white = "#e2e0f7"
 
 [colors.dim]
 black = "#322e42"
 red = "#d84f76"
 green = "#8aa872"
 yellow = "#e6a852"
 blue = "#4a869c"
 magenta = "#a580d2"
 cyan = "#7bb8c1"
 white = "#b1acde"
 
 [[colors.indexed_colors]]
 index = 16
 color = "#ea9a97"
 
 [[colors.indexed_colors]]
 index = 17
 color = "#eb98c3"

## Option 2: terafox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/terafox/alacritty.toml

# [colors.primary]
# background = "#152528"
# foreground = "#e6eaea"
# dim_foreground = "#cbd9d8"
# bright_foreground = "#eaeeee"
# 
# [colors.cursor]
# text = "#e6eaea"
# cursor = "#cbd9d8"
# 
# [colors.vi_mode_cursor]
# text = "#e6eaea"
# cursor = "#a1cdd8"
# 
# [colors.search.matches]
# foreground = "#e6eaea"
# background = "#425e5e"
# 
# [colors.search.focused_match]
# foreground = "#e6eaea"
# background = "#7aa4a1"
# 
# [colors.footer_bar]
# foreground = "#e6eaea"
# background = "#254147"
# 
# [colors.hints.start]
# foreground = "#e6eaea"
# background = "#ff8349"
# 
# [colors.hints.end]
# foreground = "#e6eaea"
# background = "#254147"
# 
# [colors.selection]
# text = "#e6eaea"
# background = "#293e40"
# 
# [colors.normal]
# black = "#2f3239"
# red = "#e85c51"
# green = "#7aa4a1"
# yellow = "#fda47f"
# blue = "#5a93aa"
# magenta = "#ad5c7c"
# cyan = "#a1cdd8"
# white = "#ebebeb"
# 
# [colors.bright]
# black = "#4e5157"
# red = "#eb746b"
# green = "#8eb2af"
# yellow = "#fdb292"
# blue = "#73a3b7"
# magenta = "#b97490"
# cyan = "#afd4de"
# white = "#eeeeee"
# 
# [colors.dim]
# black = "#282a30"
# red = "#c54e45"
# green = "#688b89"
# yellow = "#d78b6c"
# blue = "#4d7d90"
# magenta = "#934e69"
# cyan = "#89aeb8"
# white = "#c8c8c8"
# 
# [[colors.indexed_colors]]
# index = 16
# color = "#ff8349"
# 
# [[colors.indexed_colors]]
# index = 17
# color = "#cb7985"
# 


## Other Alacritty Config

[env]
TERM = "xterm-256color"

[font.normal]
family = "Inconsolata Nerd Font Mono"

[scrolling]
history = 50000


[mouse]
hide_when_typing = true

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[keyboard]
# I generally don't use vi mode in alacritty in favor of zsh vi mode and tmux, but just in case
# I am rebinding this because of one password ctrl+shift+space keybind
bindings = [
      { key = "Space", mods = "Control|Alt", action= "ToggleViMode"},
]
