#!/bin/bash
# xsel | festival --tts

# init conda for this script
source /etc/profile.d/conda.sh

# must activate the pb env before running piper which is installed in the pb env
conda activate piper

##  substitute punctuation with semicolons
input=$(xsel)
output="${input//\!/\;}"
output="${output//\?/\;}"
output="${output//\./\;}"

echo "$output"


echo "$output" | piper \
   --model /home/pedro/models/piper/en_US-lessac-high.onnx \
   --output_file - | ffplay -nodisp -autoexit -loglevel quiet -i -
